/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package MainUI;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Indatech
 */
public class MainUIView extends javax.swing.JFrame {
   

    /**
     * Creates new form MainUIView
     */
    public MainUIView() {
        initComponents();
        setTitle("Proyecto Operativos");
        setMaximumSize(new Dimension(680, 500));
        setDefaultCloseOperation(MainUIView.EXIT_ON_CLOSE);
        int lastNumber;
        while (true) {
            try {
                String input = JOptionPane.showInputDialog("Ingresa la cédula:");
                int userInput = Integer.parseInt(input);
                // Check if the input is negative
                if (userInput >= 0) {
                    // Get the last digit of the cédula
                     lastNumber = Character.getNumericValue(input.charAt(input.length() - 1));
                    break;
                }
                // Optionally, you can break the loop or continue to ask for more input
                // break; // Uncomment this if you want to exit after the first valid input
                
            } catch (NumberFormatException e) {
                // Handle the case where the input is not a valid integer
                JOptionPane.showMessageDialog(null, "Error: Debes ingresar un número válido.");
            } catch (Exception e) {
                // Handle any other unexpected exceptions
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }

        SpinnerNumberModel modeloSpinner1 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner2 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner3 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner4 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner5 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner6 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner7 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner8 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner9 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        SpinnerNumberModel modeloSpinner10 = new SpinnerNumberModel(1, 1, 12+lastNumber, 1);
        
         this.InputMSI1.setModel(modeloSpinner1);
         this.InputMSI2.setModel(modeloSpinner2);
         this.InputMSI3.setModel(modeloSpinner3);
         this.InputMSI4.setModel(modeloSpinner4);
         this.InputMSI5.setModel(modeloSpinner5);
         this.InputHP1.setModel(modeloSpinner6);
         this.InputHP2.setModel(modeloSpinner7);
         this.InputHP3.setModel(modeloSpinner8);
         this.InputHP4.setModel(modeloSpinner9);
         this.InputHP5.setModel(modeloSpinner10);
       System.out.println("sisssss");
      
         
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        InputMSI1 = new javax.swing.JSpinner();
        InputMSI2 = new javax.swing.JSpinner();
        InputMSI3 = new javax.swing.JSpinner();
        InputMSI4 = new javax.swing.JSpinner();
        InputMSI5 = new javax.swing.JSpinner();
        InputHP2 = new javax.swing.JSpinner();
        InputHP1 = new javax.swing.JSpinner();
        InputHP3 = new javax.swing.JSpinner();
        InputHP4 = new javax.swing.JSpinner();
        InputHP5 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Hp_label = new javax.swing.JMenu();
        Lenovo_label = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setText("jLabel1");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("CONFIGURACION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(java.awt.Color.black);
        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Placa base");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Memoria RAM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ensambladores");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("CPUs");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Fuente de alimentación");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        InputMSI1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        InputMSI1.setToolTipText("");
        InputMSI1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                InputMSI1StateChanged(evt);
            }
        });
        jPanel1.add(InputMSI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));
        jPanel1.add(InputMSI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));
        jPanel1.add(InputMSI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));
        jPanel1.add(InputMSI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));
        jPanel1.add(InputMSI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));
        jPanel1.add(InputHP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));
        jPanel1.add(InputHP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));
        jPanel1.add(InputHP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));
        jPanel1.add(InputHP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));
        jPanel1.add(InputHP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Placa base");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Ensambladores");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Memoria RAM");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, 40));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Fuente de alimentación");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 40));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("CPUs");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("MSI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("HP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 440));

        jMenu1.setText("INICIO");
        jMenuBar1.add(jMenu1);

        Hp_label.setText("HP");
        Hp_label.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Hp_labelMenuSelected(evt);
            }
        });
        Hp_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hp_labelMouseClicked(evt);
            }
        });
        jMenuBar1.add(Hp_label);

        Lenovo_label.setText("LENOVO");
        Lenovo_label.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Lenovo_labelMenuSelected(evt);
            }
        });
        Lenovo_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lenovo_labelMouseClicked(evt);
            }
        });
        jMenuBar1.add(Lenovo_label);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Hp_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hp_labelMouseClicked
        // TODO add your handling code here:
        System. out. println("hp");
    }//GEN-LAST:event_Hp_labelMouseClicked

    private void Hp_labelMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Hp_labelMenuSelected
        // TODO add your handling code here:

    }//GEN-LAST:event_Hp_labelMenuSelected

    private void Lenovo_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lenovo_labelMouseClicked
        // TODO add your handling code here:
         System. out. println("lenovo");
    }//GEN-LAST:event_Lenovo_labelMouseClicked

    private void Lenovo_labelMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Lenovo_labelMenuSelected

        // TODO add your handling code here:
    }//GEN-LAST:event_Lenovo_labelMenuSelected

    private void InputMSI1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_InputMSI1StateChanged
        System.out.print(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_InputMSI1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUIView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Hp_label;
    private javax.swing.JSpinner InputHP1;
    private javax.swing.JSpinner InputHP2;
    private javax.swing.JSpinner InputHP3;
    private javax.swing.JSpinner InputHP4;
    private javax.swing.JSpinner InputHP5;
    private javax.swing.JSpinner InputMSI1;
    private javax.swing.JSpinner InputMSI2;
    private javax.swing.JSpinner InputMSI3;
    private javax.swing.JSpinner InputMSI4;
    private javax.swing.JSpinner InputMSI5;
    private javax.swing.JMenu Lenovo_label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

